config/routes.rb
Rails.application.routes.draw do
  root 'graphs#index'

  resources :graphs

  get '/graphs/:id/browse', to: 'graphs#browse', as: 'browse'
  get '/graphs/:id/browse/:term', to: 'graphs#browse', as: 'browse_term'

  get '/graphs/:id/query', to: 'graphs#query', as: 'query'
  get '/graphs/:id/export', to: 'graphs#export', as: 'export'
  post '/graphs/:id/sparql', to: 'graphs#sparql', as: 'sparql'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/graph.rb
class Graph < ApplicationRecord
  attr_accessor :graph_file

  has_many :triples, dependent: :destroy
  has_many :prefixes, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :iri, :original_file, :generated_at, presence: true

  before_validation :generate_graph, if: -> { graph_file.present? }

  def grapher
    @grapher ||= Rails.cache.fetch(self) do
      Grapher.from_triples(triples)
    end
  end

  def prefix_string
    "#{prefixes.map(&:to_s).join("\n")}\n\n"
  end

  # Create a heirachy of all the subjects in the graph
  #
  # 1. Build a map of all potential parents and their children
  # 2. Find all the top level subjects by removing all URI's that are subclasses of another
  # 3. Find all the children of the top level subjects, and their children, and so on
  def heirachy
    child_map = triples.sub_classes.each_with_object({}) do |triple, hsh|
      hsh[triple.object_uri_identifier] ||= []
      hsh[triple.object_uri_identifier] << triple.subject_uri_identifier
    end

    child_map[:top_level] = child_map.keys - child_map.values.flatten

    recursive_heirachy(:top_level, child_map)
  end

  private

  def graph_labels
    @graph_labels ||= triples.labels.to_h do |triple|
      [triple.subject_uri_identifier, triple.object[1..-2]]
    end
  end

  def recursive_heirachy(subject, child_map)
    children = child_map[subject]

    return if children.blank?

    children.each_with_object({}) do |child_subject, hsh|
      label = graph_labels[child_subject] || child_subject

      hsh[[label, child_subject]] = recursive_heirachy(child_subject, child_map)
    end
  end

  def generate_graph
    graph_tripples_and_prefixes

    self.original_file = graph_file.original_filename
    self.generated_at  = Time.now
  end

  def graph_tripples_and_prefixes
    grapher = Grapher.from_file(graph_file.tempfile)

    grapher.graph.each_statement do |statement|
      triples << Triple.from_statement(statement)
    end

    grapher.prefixes.each { |prefix, uri| prefixes.build(prefix:, uri:) }
  end
end

app/models/triple.rb
# Stores all graph triples
class Triple < ApplicationRecord
  belongs_to :graph

  scope :sub_classes, -> { where(predicate: '<http://www.w3.org/2000/01/rdf-schema#subClassOf>') }
  scope :labels, -> { where(predicate: '<http://www.w3.org/2000/01/rdf-schema#label>') }

  # Create a triple from an RDF statement
  def self.from_statement(statement)
    subject   = RDF::NTriples.serialize(statement.subject)
    predicate = RDF::NTriples.serialize(statement.predicate)
    object    = RDF::NTriples.serialize(statement.object)

    new(subject:, predicate:, object:)
  end

  def subject_uri_identifier
    subject.match(/<(.*)#(.*)>/)[2]
  end

  def object_uri_identifier
    object.match(/<(.*)#(.*)>/)[2]
  end

  def to_s
    "#{subject} #{predicate} #{object} ."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  before_action :set_graph, only: %w[show destroy query sparql export browse]

  def create
    @graph = Graph.new(graph_params)

    if @graph.save
      redirect_to @graph
    else
      render :new, status: :unprocessable_entity
    end
  end

  def browse
    @term = params[:term]
  end

  def sparql
    grapher = @graph.grapher
    result  = grapher.sparql(params[:query])

    render ResultSetComponent.new(result), layout: false
  end

  def export
    nt_content = @graph.triples.map { |triple| triple.to_s }.join("\n")

    send_data nt_content, type: 'text/nt; charset=utf-8; header=present',
                          disposition: "attachment; filename=#{@graph.name}.nt"
  end

  def new
    @graph = Graph.new
  end

  def destroy
    @graph.destroy

    redirect_to graphs_path
  end

  private

  def set_graph
    @graph = Graph.find(params[:id] || params[:graph_id])
  end

  def graph_params
    params.require(:graph).permit(:name, :graph_file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def svg(path)
    File.open("app/assets/images/#{path}.svg", 'rb') do |file|
      raw file.read
    end
  end
end

app/views/application/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="text-red-600 uppercase py-1 mb-1 font-bold text-xs">
    <ul>
      <% resource.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/graphs/index.html.erb
hi

app/views/graphs/new.html.erb
<h2>Create a new graph</h2>
<div class="px-1 py-2">
  <%= form_for(@graph) do |form| %>
    <%= render "error_messages", resource: @graph %>
    <%= form.label(:name) %>
    <%= form.text_field(:name) %>

    <%= form.label(:graph_file) %>
    <%= form.file_field(:graph_file, accept: '.rdf') %>

    <%= form.submit %>
  <% end %>
</div>

app/views/graphs/query.html.erb
<section data-controller="sparql"
         data-sparql-url-value='<%= sparql_path(@graph) %>'
         data-sparql-prefix-value='<%= @graph.prefix_string %>'>

  <div data-sparql-target="query"></div>
  <div data-action="click->sparql#query" class="button my-2">EXECUTE</div>

  <div data-sparql-target="results"></div>
</section>

app/views/graphs/show.html.erb
<h2><%= @graph.name %></h2>

<%= render ListComponent.new do |list| %>
  <% list.with_item('IRI', @graph.iri) %>
  <% list.with_item('Triples', @graph.triples.size) %>
  <% list.with_item('Generated', @graph.generated_at) %>
  <% list.with_item('Original File', @graph.original_file) %>
<% end %>

<div class="flex justify-between">
  <div class="flex">
    <a href="<%= browse_path(@graph) %>" class="mr-2 button bg-green-800 hover:bg-green-900">Browse</a>
    <a href="<%= query_path(@graph) %>" class="mr-2 button bg-blue-800 hover:bg-blue-900">Query</a>
    <a href="<%= export_path(@graph) %>" class="mr-2 button bg-orange-800 hover:bg-orange-900">Export triples</a>
  </div>

  <%= button_to "delete", @graph, class: 'button bg-red-800 hover:bg-red-900', method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RYAN RDF</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class='bg-primary text-gray-300'>
    <div class='bg-secondary border-b border-border uppercase font-bold flex items-center justify-between h-8'>
      <div class='flex items-center ml-4'>
        <span class='icon'><%= svg(:table) %></span>
        <span class='ml-3'><a href="<%= root_path %>">Ryan RDF</a></span>
      </div>
      <div>
        <%= render GraphMenuComponent.new %>
      </div>
    </div>

    <section class="mx-auto my-5 w-4/5">
      <%= yield %>
    </section>
  </body>
</html>